### ISSUE TITLE
Failed to activate the sublime package

### ISSUE THREAD

**Issue by smitzter** [idleberg/atom-sublime#1]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.17.2 x64
**Electron**: 1.3.15
**OS**: Microsoft Windows 10 Home
**Thrown From**: [sublime](https://github.com/idleberg/atom-sublime) package 0.5.0

### Stack Trace

Failed to activate the sublime package

```
At Cannot find module 'atom-package-deps'

Error: Cannot find module 'atom-package-deps'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.get_Module._resolveFilename (~/AppData/Local/atom/app-1.17.2/resources/app/src/module-cache.js:354:1)
    at Module.require (~/AppData/Local/atom/app-1.17.2/resources/app/static/index.js:40:43)
    at require (~/AppData/Local/atom/app-1.17.2/resources/app/src/native-compile-cache.js:66:1)
    at Object.activate (/packages/sublime/lib/sublime.coffee:5:5)
    at Package.module.exports.Package.activateNow (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:253:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:225:1
    at Package.module.exports.Package.measure (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:99:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:218:1
    at Package.module.exports.Package.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package.js:215:1)
    at PackageManager.module.exports.PackageManager.activatePackage (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:642:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:623:1
    at Config.module.exports.Config.transactAsync (~/AppData/Local/atom/app-1.17.2/resources/app/src/config.js:346:1)
    at PackageManager.module.exports.PackageManager.activatePackages (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:618:1)
    at PackageManager.module.exports.PackageManager.activate (~/AppData/Local/atom/app-1.17.2/resources/app/src/package-manager.js:600:1)
    at ~/AppData/Local/atom/app-1.17.2/resources/app/src/atom-environment.js:832:1
```

### Commands

```
```

### Non-Core Packages

```
sublime 0.5.0 
```

**Comment by idleberg** [comment]
Did you install it [using git](https://github.com/idleberg/atom-sublime#using-git)?
